name: Deploy to ECS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download current ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ecs-app \
            --query taskDefinition \
            > task-definition.json

      - name: Render new ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: threatmod-container
          image: my-image

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: threatmod-service
          cluster: threatmod-cluster
          wait-for-service-stability: true